version: 2.1

orbs:
  node: circleci/node@7.1.0
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.7.0
    executor: gh-pages/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run: |
          yarn build
      - gh-pages/deploy:
          build-dir: ./build
          ssh-fingerprints: SHA256:yFTrxSYpoOmHmgkpCKVVQ69ZI7XHGJd9pE/6zBD3DJE anton@pendle.finance

workflows:
  Publish to Github Pages:
      jobs:
        - deploy:
            filters:
              branches:
                only: main
